### ISSUE TITLE
Problem when installing on OS X

### ISSUE THREAD

**Issue by arthursw** [assembl/assembl#120]
I am trying to install Assembl on OS X.

I run:
```
git clone https://github.com/assembl/assembl.git
cd assembl
fab -c configs/mac.rc install_single_server
```
And I get the following error:
```
[localhost] Executing task 'update_python_package_builddeps'
[localhost] Executing task 'app_setup'
[localhost] run: cd /Users/Arthur/Projects/assembl && . /Users/Arthur/Projects/assembl/venv/bin/activate && pip install -e ./
[localhost] out: Obtaining file:///Users/Arthur/Projects/assembl
[localhost] out: Requirement already satisfied: pip==9.0.1 in ./venv/lib/python2.7/site-packages (from assembl==0.0)

[...]

[localhost] out: Collecting fuxi (from assembl==0.0)
[localhost] out:   Using cached FuXi-1.0-rc.dev.tar.gz
[localhost] out:     Complete output from command python setup.py egg_info:
[localhost] out:     Traceback (most recent call last):
[localhost] out:       File "<string>", line 1, in <module>
[localhost] out:       File "/private/var/folders/sz/f97g80v149b689p1jvnwybgr0000gn/T/pip-build-Nu21hx/fuxi/setup.py", line 1, in <module>
[localhost] out:         import ez_setup
[localhost] out:     ImportError: No module named ez_setup
[localhost] out:     ----------------------------------------
[localhost] out: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sz/f97g80v149b689p1jvnwybgr0000gn/T/pip-build-Nu21hx/fuxi/
[localhost] out: 

Fatal error: run() received nonzero return code 1 while executing!

Requested: cd /Users/Arthur/Projects/assembl && . /Users/Arthur/Projects/assembl/venv/bin/activate && pip install -e ./
Executed: /bin/bash -l -c "cd /Users/Arthur/Projects/assembl && . /Users/Arthur/Projects/assembl/venv/bin/activate && pip install -e ./"

Aborting.
Disconnecting from localhost... done.
```

Note that something else went wrong before that: the `virtualenv` was not created (`venv/bin/activate` was not created, this was a problem at some point when running `fab -c configs/mac.rc install_single_server` ). 

On line `505` of the `fabfile.py` `real_prefix` is defined (because of `fabric` on OS X?) although no `virtualenv` is installed, so the `virtualenv` creation is ignored. 

I had to comment line `505` to `509`:
```python
    This is incorrect, it will check locally instead fo on the remote server
    if hasattr(sys, 'real_prefix'):
        print(cyan('The virtualenv seems to already exist, so we don\'t try to create it again'))
        print(cyan('(otherwise the virtualenv command would produce an error)'))
        return
```
and call `fab -c configs/mac.rc build_virtualenv` to properly build the `virtualenv`.

Now I can activate the `virtualenv` with `source venv/bin/activate`, but it does not help to `install_single_server` (same error with `fab -c configs/mac.rc install_single_server`).

**Comment by n0izn0iz** [comment]
Hi, I think this issue was fixed by https://github.com/assembl/assembl/commit/5a1b7c1591c84de12bc9623931d067f9df5fbdc1
Could you try again please?

**Comment by arthursw** [comment]
I just checked, I went further but it's not working 100% yet.

When running `fab -c configs/mac.rc install_single_server`:

First, I still had the issue when it tries to install node while I use nvm. I had to manually install node v8.1.4 with `nvm install v8.1.4`.

Then it went further but got stuck because I didn't have `pip` in `/usr/local/bin/pip`. Instead, since I have multiple versions of python installed, I had `pip2`, `pip2.7` and `pip3` in `/usr/local/bin/` as explained in [this stackoverflow question (see third comment)](https://stackoverflow.com/a/11272201/719276). So I duplicated `pip2.7` and renamed it to `pip`.

Then the command `fab -c configs/mac.rc install_single_server` executed successfully.

Now, when running `fab -c configs/mac.rc bootstrap_from_checkout`, I get the following error:
```
[...]
Database created successfully!
Installing database
[localhost] run: cd /Users/Arthur/Projects/assembl && . /Users/Arthur/Projects/assembl/venv/bin/activate && assembl-db-manage local.ini bootstrap
[localhost] out: /Users/Arthur/Projects/assembl/assembl/alembic/versions/238823d75893_notification_subscriptions.py:20: SyntaxWarning: import * only allowed at module level
[localhost] out:   def upgrade(pyramid_env):
[localhost] out: /Users/Arthur/Projects/assembl/assembl/alembic/versions/33c20d131cb6_fix_notification_constraints.py:21: SyntaxWarning: import * only allowed at module level
[localhost] out:   def upgrade(pyramid_env):
[localhost] out: /Users/Arthur/Projects/assembl/assembl/alembic/versions/5592fcf1c810_notifications_classes.py:21: SyntaxWarning: import * only allowed at module level
[localhost] out:   def upgrade(pyramid_env):
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Content|content being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Post|post being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|AssemblPost|assembl_post being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|SynthesisPost|synthesis_post being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|PropositionPost|assembl_post being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|WidgetPost|post_with_metadata being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|IdeaProposalPost|idea_proposal_post being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|ImportedPost|imported_post being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Email|email being replaced with new property Content.widget_idea_links; the old property will be discarded
[localhost] out:   prop,
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py:1741: SAWarning: Warning: relationship 'discussion' on mapper 'Mapper|TableOfContents|table_of_contents' supersedes the same relationship on inherited mapper 'Mapper|IdeaGraphView|idea_graph_view'; this can cause dependency issues during flush
[localhost] out:   % (self.key, self.parent, inheriting))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py:1741: SAWarning: Warning: relationship 'discussion' on mapper 'Mapper|Extract|extract' supersedes the same relationship on inherited mapper 'Mapper|IdeaContentPositiveLink|idea_content_positive_link'; this can cause dependency issues during flush
[localhost] out:   % (self.key, self.parent, inheriting))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py:1741: SAWarning: Warning: relationship 'discussion' on mapper 'Mapper|Extract|extract' supersedes the same relationship on inherited mapper 'Mapper|IdeaContentLink|idea_content_link'; this can cause dependency issues during flush
[localhost] out:   % (self.key, self.parent, inheriting))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Afrikaans'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'afrikaans'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Afrikaans (Namibia)'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Afrikaans (South Africa)'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'afrikaans (Afrique du Sud...'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'akan'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Akan-Sprache'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Arabisch (Vereinigte Arab...'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Arabic (Bahrain)'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: /Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Arabic (Algeria)'. (this warning may be suppressed after 10 occurrences)
[localhost] out:   (util.ellipses_string(value),))
[localhost] out: sent 0 * [{'@id': 'local:Permission/19', 'name': 'edit_my_extract', '@type': 'Permission'}, {'@id': 'local:Permission/4', 'name': 'edit_synthesis', '@type': 'Permission'}, {'@id': 'local:Permission/3', 'name': 'edit_idea', '@type': 'Permission'}, {'@id': 'local:Permission/2', 'name': 'add_post', '@type': 'Permission'}, {'trust_emails': True, 'provider_type': 'facebook', '@id': 'local:IdentityProvider/1', 'name': 'facebook', '@type': 'IdentityProvider'}, {'@id': 'local:Permission/14', 'name': 'edit_extract', '@type': 'Permission'}, {'@id': 'local:Permission/13', 'name': 'read', '@type': 'Permission'}, {'@id': 'local:Permission/5', 'name': 'admin_discussion', '@type': 'Permission'}, {'@id': 'local:Permission/15', 'name': 'export_post', '@type': 'Permission'}, {'@id': 'local:Permission/16', 'name': 'delete_post', '@type': 'Permission'}, {'@id': 'local:Permission/7', 'name': 'send_synthesis', '@type': 'Permission'}, {'@id': 'local:Permission/6', 'name': 'delete_my_post', '@type': 'Permission'}, {'@id': 'local:Permission/17', 'name': 'vote', '@type': 'Permission'}, {'@id': 'local:Permission/21', 'name': 'add_extract', '@type': 'Permission'}, {'trust_emails': True, 'provider_type': 'twitter', '@id': 'local:IdentityProvider/2', 'name': 'twitter', '@type': 'IdentityProvider'}, {'@id': 'local:Permission/10', 'name': 'self_register_req', '@type': 'Permission'}, {'@id': 'local:Permission/1', 'name': 'moderate_post', '@type': 'Permission'}, {'@id': 'local:Permission/8', 'name': 'discussion_stats', '@type': 'Permission'}, {'@id': 'local:Permission/20', 'name': 'read_public_cif', '@type': 'Permission'}, {'trust_emails': True, 'provider_type': 'google-oauth2', '@id': 'local:IdentityProvider/3', 'name': 'google-oauth2', '@type': 'IdentityProvider'}, {'@id': 'local:Permission/11', 'name': 'edit_post', '@type': 'Permission'}, {'@id': 'local:Permission/18', 'name': 'self_register', '@type': 'Permission'}, {'@id': 'local:Permission/9', 'name': 'add_idea', '@type': 'Permission'}, {'@id': 'local:Permission/12', 'name': 'sysadmin', '@type': 'Permission'}]
[localhost] out: 

[localhost] Executing task 'app_reload'

Warning: run() received nonzero return code 2 while executing 'cd /Users/Arthur/Projects/assembl && . /Users/Arthur/Projects/assembl/venv/bin/activate && supervisorctl avail'!

[localhost] Executing task 'webservers_reload'
```

**Comment by maparent** [comment]
Good point about pip2, corrected in 6685325c7f1af0b43ac22ecad15b485a426cc982. 
Note that this only applies to the system pip, the venv pip should still be callable by that name.
Really puzzled about the node install, it is installed locally in the venv, so you should not have to install it. Do you remember at which point it failed before you installed it?
Some of the errors are explicitly warnings, your trace did not stop the fab command, or did it?
Regards.

**Comment by swergas** [comment]
@arthursw any news about this issue?

**Comment by arthursw** [comment]
I ran the same command again :
 `fab -c configs/mac.rc bootstrap_from_checkout`

and I still have an error:

```
[...]
[localhost] run: . /Users/Arthur/Projects/assembl/venv/bin/activate && npm update
[localhost] out: - camelcase@2.1.1 node_modules/camelcase-keys/node_modules/camelcase
[localhost] out: - loader-utils@1.1.0 node_modules/css-loader/node_modules/loader-utils
[localhost] out: - memory-fs@0.2.0 node_modules/enhanced-resolve/node_modules/memory-fs
[localhost] out: - debug@2.6.7 node_modules/express/node_modules/debug
[localhost] out: - debug@2.6.7 node_modules/finalhandler/node_modules/debug
[localhost] out: - debug@2.6.7 node_modules/send/node_modules/debug
[localhost] out: - loader-utils@1.1.0 node_modules/style-loader/node_modules/loader-utils
[localhost] out: wordwrap@0.0.2 node_modules/cliui/node_modules/wordwrap -> node_modules/uglify-js/node_modules/wordwrap
[localhost] out: window-size@0.1.0 node_modules/window-size -> node_modules/uglify-js/node_modules/yargs/node_modules/window-size
[localhost] out: - source-map@0.4.4 node_modules/webpack-core/node_modules/source-map
[localhost] out: - memory-fs@0.4.1 node_modules/webpack-dev-middleware/node_modules/memory-fs
[localhost] out: - acorn@3.3.0 node_modules/webpack/node_modules/acorn
[localhost] out: - interpret@0.6.6 node_modules/webpack/node_modules/interpret
[localhost] out: - async@0.2.10 node_modules/webpack/node_modules/uglify-js/node_modules/async
[localhost] out: - uglify-js@2.7.5 node_modules/webpack/node_modules/uglify-js
[localhost] out: - lodash.flatten@4.4.0 node_modules/lodash.flatten
[localhost] out: - lodash.isequal@4.5.0 node_modules/lodash.isequal
[localhost] out: - lodash.isobject@3.0.2 node_modules/lodash.isobject
[localhost] out: - open@0.0.5 node_modules/open
[localhost] out: - pbkdf2-compat@2.0.1 node_modules/pbkdf2-compat
[localhost] out: - stream-cache@0.0.2 node_modules/stream-cache
[localhost] out: - webpack-core@0.6.9 node_modules/webpack-core
[localhost] out: assembl_v2@2.0.0 /Users/Arthur/Projects/assembl/assembl/static2
[localhost] out: +-- babel-core@6.26.0 
[localhost] out: +-- babel-loader@7.1.2 
[localhost] out: +-- babel-plugin-transform-class-properties@6.24.1 
[localhost] out: +-- babel-plugin-transform-object-rest-spread@6.26.0 
[localhost] out: +-- babel-plugin-transform-runtime@6.23.0 
[localhost] out: +-- babel-polyfill@6.26.0 
[localhost] out: +-- babel-runtime@6.26.0 
[localhost] out: +-- css-loader@0.28.5 
[localhost] out: +-- extract-text-webpack-plugin@3.0.0 
[localhost] out: +-- fbjs@0.8.14 
[localhost] out: +-- file-loader@0.11.2 
[localhost] out: +-- graphql-tools@1.2.1 
[localhost] out: +-- immutability-helper@2.3.1 
[localhost] out: +-- json-loader@0.5.7 
[localhost] out: +-- node-sass@4.5.3 
[localhost] out: +-- piwik-react-router@0.9.0  (git://github.com/assembl/piwik-react-router.git#55a93a216a23fd3058bef33b47f989f1059196a8)
[localhost] out: +-- react-apollo@1.4.14 
[localhost] out: +-- react-bootstrap@0.31.2 
[localhost] out: +-- react-redux-i18n@1.9.0 
[localhost] out: +-- sass-loader@6.0.6 
[localhost] out: +-- style-loader@0.18.2 
[localhost] out: +-- uglifyjs-webpack-plugin@1.0.0-beta.2 
[localhost] out: +-- webpack@3.5.5 
[localhost] out: `-- webpack-dev-server@2.7.1 
[localhost] out: 
[localhost] out: npm WARN assembl_v2@2.0.0 No repository field.
[localhost] out: npm ERR! Darwin 16.7.0
[localhost] out: npm ERR! argv "/Users/Arthur/Projects/assembl/venv/bin/node" "/Users/Arthur/Projects/assembl/venv/bin/npm" "update"
[localhost] out: npm ERR! node v6.1.0
[localhost] out: npm ERR! npm  v3.8.6
[localhost] out: npm ERR! path /Users/Arthur/Projects/assembl/assembl/static2/node_modules/.staging/node-pre-gyp-788fd28a
[localhost] out: npm ERR! code ENOENT
[localhost] out: npm ERR! errno -2
[localhost] out: npm ERR! syscall rename
[localhost] out: 
[localhost] out: npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Arthur/Projects/assembl/assembl/static2/node_modules/.staging/node-pre-gyp-788fd28a' -> '/Users/Arthur/Projects/assembl/assembl/static2/node_modules/fsevents/node_modules/node-pre-gyp'
[localhost] out: npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Arthur/Projects/assembl/assembl/static2/node_modules/.staging/node-pre-gyp-788fd28a' -> '/Users/Arthur/Projects/assembl/assembl/static2/node_modules/fsevents/node_modules/node-pre-gyp'
[localhost] out: npm ERR! enoent This is most likely not a problem with npm itself
[localhost] out: npm ERR! enoent and is related to npm not being able to find a file.
[localhost] out: npm ERR! enoent 
[localhost] out: 
[localhost] out: npm ERR! Please include the following file with any support request:
[localhost] out: npm ERR!     /Users/Arthur/Projects/assembl/assembl/static2/npm-debug.log
[localhost] out: 


Fatal error: run() received nonzero return code 254 while executing!

Requested: . /Users/Arthur/Projects/assembl/venv/bin/activate && npm update
Executed: /bin/bash -l -c "cd /Users/Arthur/Projects/assembl/assembl/static2 >/dev/null && . /Users/Arthur/Projects/assembl/venv/bin/activate && npm update"

Aborting.
Disconnecting from localhost... done.
```

Any idea?

**Comment by maparent** [comment]
Hmmm... Maybe an artifact from a previous build? try deleting /Users/Arthur/Projects/assembl/assembl/static2/node_modules

**Comment by vincentfretin** [comment]
Norman had the same issue on macOS. This is since I updated webpack.
As far as I remember what Norman said, the error seems to appear only the second time you run yarn in the static2 folder (or via fab)
If you start fresh by removing node_modules, it was ok.

Can you try to remove /Users/Arthur/Projects/assembl/assembl/static2/node_modules/.staging and/or /Users/Arthur/Projects/assembl/assembl/static2/node_modules/fsevents/node_modules/node-pre-gyp ?
The error seems to be that /Users/Arthur/Projects/assembl/assembl/static2/node_modules/fsevents/node_modules/node-pre-gyp is missing? and so can't create the symlink? Is this folder missing?

**Comment by vincentfretin** [comment]
I just did a big merge on develop with lots of updated packages. Can you please try again? removing static2/node_modules, and reexecuting the fab command twice?

**Comment by arthursw** [comment]
Ok, the command `fab -c configs/mac.rc bootstrap_from_checkout` seems to finish properly now.

Then I run:

```
source venv/bin/activate
supervisord
```

Now, when I try to create a new user, I get this error:
```
(venv) Arthur:assembl Arthur$ assembl-add-user --email arthur.sw@gmail.com --name "Arthur Masson" --username arthur.sw --password PASSWORD local.ini
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Content|content being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Post|post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|AssemblPost|assembl_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|SynthesisPost|synthesis_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|PropositionPost|assembl_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|WidgetPost|post_with_metadata being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|IdeaProposalPost|idea_proposal_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|ImportedPost|imported_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Email|email being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
Traceback (most recent call last):
  File "/Users/Arthur/Projects/assembl/venv/bin/assembl-add-user", line 11, in <module>
    load_entry_point('assembl', 'console_scripts', 'assembl-add-user')()
  File "/Users/Arthur/Projects/assembl/assembl/scripts/add_user.py", line 58, in main
    env = bootstrap(args.configuration)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/pyramid/paster.py", line 135, in bootstrap
    app = get_app(config_uri, options=options)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/pyramid/paster.py", line 31, in get_app
    global_conf=options)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/Arthur/Projects/assembl/assembl/__init__.py", line 69, in main
    config.include('.models')
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 800, in include
    c(configurator)
  File "/Users/Arthur/Projects/assembl/assembl/models/__init__.py", line 317, in includeme
    config.include('.preferences')
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 800, in include
    c(configurator)
  File "/Users/Arthur/Projects/assembl/assembl/models/preferences.py", line 848, in includeme
    k: k for k in get_active_auth_strategies(settings)}
  File "/Users/Arthur/Projects/assembl/assembl/models/preferences.py", line 848, in <dictcomp>
    k: k for k in get_active_auth_strategies(settings)}
  File "/Users/Arthur/Projects/assembl/assembl/auth/social_auth.py", line 260, in get_active_auth_strategies
    all_backends = load_backends(settings.get('SOCIAL_AUTH_AUTHENTICATION_BACKENDS'))
  File "/Users/Arthur/Projects/assembl/venv/src/python-social-auth/social/backends/utils.py", line 33, in load_backends
    backend = module_member(auth_backend)
  File "/Users/Arthur/Projects/assembl/venv/src/python-social-auth/social/utils.py", line 56, in module_member
    module = import_module(mod)
  File "/Users/Arthur/Projects/assembl/venv/src/python-social-auth/social/utils.py", line 50, in import_module
    __import__(name)
  File "/Users/Arthur/Projects/assembl/venv/src/python-social-auth/social/backends/saml.py", line 10, in <module>
    from onelogin.saml2.auth import OneLogin_Saml2_Auth
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 17, in <module>
    from onelogin.saml2.settings import OneLogin_Saml2_Settings
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/onelogin/saml2/settings.py", line 20, in <module>
    from onelogin.saml2.metadata import OneLogin_Saml2_Metadata
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/onelogin/saml2/metadata.py", line 17, in <module>
    from onelogin.saml2.utils import OneLogin_Saml2_Utils
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/onelogin/saml2/utils.py", line 31, in <module>
    import dm.xmlsec.binding as xmlsec
  File "/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/dm/xmlsec/binding/__init__.py", line 2, in <module>
    from _xmlsec import *
  File "_xmlsec.pyx", line 32, in init dm.xmlsec.binding._xmlsec (src/_xmlsec.c:10665)
ImportError: lxml.etree does not export expected C function adoptExternalDocument
```

Then I start the development server with `supervisorctl start dev:`, but I get `ERR_CONNECTION_REFUSED` when connecting to `http://localhost:6543/`.

**Comment by vincentfretin** [comment]
Are you using master or develop?
I think @maparent fixed this dm.xmlsec.binding._xmlsec issue on develop.

**Comment by vincentfretin** [comment]
try removing venv and execute fab again to be sure dm.xmlsec.binding and lxml are properly installed.

**Comment by arthursw** [comment]
I am on branch `develop` (up-to-date).

Ok, now when I create a user I get `ERROR: Initialized twice.`:

```
assembl-add-user --email arthurpub.sw@gmail.com --name "Arthur Masson 2" --username arthursw --password PASSWORD local.ini

/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Content|content being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Post|post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|AssemblPost|assembl_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|SynthesisPost|synthesis_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|PropositionPost|assembl_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|WidgetPost|post_with_metadata being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|IdeaProposalPost|idea_proposal_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|ImportedPost|imported_post being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1599: SAWarning: Property Content.widget_idea_links on Mapper|Email|email being replaced with new property Content.widget_idea_links; the old property will be discarded
  prop,
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py:1741: SAWarning: Warning: relationship 'discussion' on mapper 'Mapper|TableOfContents|table_of_contents' supersedes the same relationship on inherited mapper 'Mapper|IdeaGraphView|idea_graph_view'; this can cause dependency issues during flush
  % (self.key, self.parent, inheriting))
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py:1741: SAWarning: Warning: relationship 'discussion' on mapper 'Mapper|Extract|extract' supersedes the same relationship on inherited mapper 'Mapper|IdeaContentPositiveLink|idea_content_positive_link'; this can cause dependency issues during flush
  % (self.key, self.parent, inheriting))
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py:1741: SAWarning: Warning: relationship 'discussion' on mapper 'Mapper|Extract|extract' supersedes the same relationship on inherited mapper 'Mapper|IdeaContentLink|idea_content_link'; this can cause dependency issues during flush
  % (self.key, self.parent, inheriting))
EMPTY CDICT!
initialized twice: {'mail.port': '8025', 'tm.attempts': '2', 'SOCIAL_AUTH_FACEBOOK_SCOPE': 'public_profile\nemail', 'SOCIAL_AUTH_TWITTER_SECRET': '...', 'celery_tasks.broker': 'redis://localhost:6379/0', 'subscriptions.participant.default': 'FOLLOW_SYNTHESES\nEMAIL_BOUNCED\nEMAIL_VALIDATE\nPARTICIPATED_FOR_FIRST_TIME_WELCOME\nSUBSCRIPTION_WELCOME', 'webpack_host': 'localhost', 'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET': '...', 'changes.websocket.port': '8085', 'facebook.debug_mode': 'true', 'sqlalchemy.strategy': 'atexit_cleanup', 'facebook.export_permissions': 'public_profile, email, publish_actions, user_posts, user_likes, manage_pages, publish_pages, user_groups, user_managed_groups', 'SOCIAL_AUTH_WORDPRESS_OAUTH2_SECRET': '....', 'login_providers': 'facebook twitter google-oauth2', 'beaker.session.lock_dir': '/Users/Arthur/Projects/assembl/var/sessions/lock', 'celery_tasks.imap.num_workers': '1', 'sqlalchemy.url': 'postgresql+psycopg2://assembl:assembl@localhost/assembl?sslmode=disable', '__file__': '/Users/Arthur/Projects/assembl/local.ini', 'jinja2.directories': 'assembl:templates', 'sqlalchemy.echo': 'False', 'USE_UNIQUE_USER_ID': 'True', 'activate_tour': 'true', 'dogpile_cache.backend': 'file', 'elasticsearch_host': 'localhost', 'celery_tasks.imap.imodeleventwatcher': 'assembl.tasks.notification_dispatch.ModelEventWatcherCelerySender', 'mail.host': 'localhost', 'SOCIAL_AUTH_SAML_SP_ENTITY_ID': 'http://saml.localhost', 'elasticsearch_index': 'assembl', 'redis_host': 'localhost', 'celery_tasks.notification_dispatch.num_workers': '1', 'SOCIAL_AUTH_FACEBOOK_SECRET': '...', 'SOCIAL_AUTH_FACEBOOK_KEY': '...', 'assembl_handle_exceptions': 'false', 'assembl.imodeleventwatcher': 'assembl.tasks.notification_dispatch.ModelEventWatcherCelerySender', 'require_secure_connection': 'false', 'random_file': 'random.ini', 'changes.multiplex': 'true', 'ini_files': 'production.ini develop_overlay.ini RANDOM:random.ini.tmpl RC_DATA', 'web_analytics_piwik_api_token': '', 'handle_exceptions': '', 'debugtoolbar.intercept_exc': 'display', 'db_schema': 'public', 'public_hostname': 'localhost', 'changes.websocket.proxied': 'false', 'session.secret': 'FTIapirL5xElIRn9nopUJEv5D8W/5UtqBndrv8xGHiYSQkNELZiq4jq2xS8WDjev25ZrvkHdI8scU7MghSIzddF5', 'raven_url': '', 'public_port': '6543', 'SOCIAL_AUTH_GITHUB_SECRET': '...', 'piwik_host': 'localhost', 'IGNORE_DEFAULT_SCOPE': 'True', 'SOCIAL_AUTH_USER_MODEL': 'assembl.models.auth.User', 'use_elasticsearch': 'true', 'trusted_login_providers': 'facebook\ngoogle-oauth2\ntwitter\nsaml', 'pyramid.includes': '\npyramid_mailer.debug\npyramid_debugtoolbar\npyramid_debugtoolbar_ajax\npyramid_tm', 'use_webpack_server': 'true', 'SOCIAL_AUTH_TWITTER_KEY': '...', 'SOCIAL_AUTH_FIELDS_STORED_IN_SESSION': 'next_view', 'here': '/Users/Arthur/Projects/assembl', 'web_analytics_piwik_url': '', 'beaker.session.url': 'localhost:11211', 'security.email_token_salt': 'FiMpWpy/GBs6jsQJq4+D1os97n+9sXxf6zaFJVYIonulX0kWqW7+atdEokBV1j0xa8pAlkydBoSKclvZ94guQKxW', 'avatar.gravatar_default': 'mm', 'beaker.session.cookie_on_exception': 'true', 'discussion_callbacks': '\nassembl.lib.discussion_creation.DiscussionCreationPrinter', 'SOCIAL_AUTH_LOGIN_URL': '/login', 'pyramid.debug_routematch': 'true', 'changes.socket': 'ipc:///tmp/assembl_changes/0', 'imap_host': 'localhost', 'changes.prefix': '/socket', 'SOCIAL_AUTH_GITHUB_SCOPE': 'repo', 'mac': 'false', 'db_user': 'assembl', 'db_host': 'localhost', 'pyramid.debug_notfound': 'true', 'changes.websocket.url': '//localhost:6543/socket/', 'debugtoolbar.enabled': 'true', 'celery_tasks.notify.imodeleventwatcher': 'assembl.lib.model_watcher.ModelEventWatcherPrinter', 'beaker.session.elevated_expires': '2635200', 'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY': '...', 'default_theme': 'default', 'auth_policy_class': 'assembl.auth.util.UpgradingTokenSessionAuthenticationPolicy', 'pyramid.reload_templates': 'true', 'SOCIAL_AUTH_LOGGEDIN_FUNCTION': 'assembl.auth.social_auth.login_required', 'webpack_port': '8080', 'SOCIAL_AUTH_STORAGE': 'assembl.models.social_auth.AssemblStorage', 'SOCIAL_AUTH_USER_FIELDS': 'email\nfullname', 'mysql_host': 'localhost', 'assembl_debug_signal': 'true', 'use_source_reader_for_mail': 'false', 'supported_exports_list': '', 'SOCIAL_AUTH_STRATEGY': 'assembl.auth.social_auth.AssemblStrategy', 'store': 'sqlalchemy', 'beaker.session.encrypt_key': '3FWsr87k7KtIzp3c9wBd5onSD0NVvnAC22v3ghP3ZDniI3umkslDSUkeBwZRAO3w7KlWiMgJaQNnFUKq1/SmKOMw', 'pyramid.default_locale_name': 'en_CA', 'celery_tasks.translate.imodeleventwatcher': 'assembl.lib.model_watcher.ModelEventWatcherPrinter', 'available_languages': 'fr_CA en_CA de', 'sentry_scheme': 'https', 'pyramid.debug_all': 'true', 'dogpile_cache.arguments.filename': 'var/dogpile_cache.dbm', 'sentry_host': 'localhost', 'debugtoolbar.hosts': '127.0.0.0/8', 'cache_viewdefs': 'false', 'SOCIAL_AUTH_WORDPRESS_OAUTH2_KEY': '....', 'web_analytics_piwik_script': '', 'redis_socket': '0', 'SOCIAL_AUTH_AUTHENTICATION_BACKENDS': 'assembl.auth.wordpress.WordPressServerOAuth2\nsocial.backends.twitter.TwitterOAuth\nsocial.backends.open_id.OpenIdAuth\nsocial.backends.google.GoogleOpenId\nsocial.backends.google.GoogleOAuth2\nsocial.backends.google.GoogleOAuth\nsocial.backends.yammer.YammerOAuth2\nsocial.backends.yahoo.YahooOpenId\nsocial.backends.stripe.StripeOAuth2\nsocial.backends.persona.PersonaAuth\nsocial.backends.facebook.FacebookOAuth2\nsocial.backends.facebook.FacebookAppOAuth2\nsocial.backends.yahoo.YahooOAuth\nsocial.backends.angel.AngelOAuth2\nsocial.backends.behance.BehanceOAuth2\nsocial.backends.bitbucket.BitbucketOAuth\nsocial.backends.box.BoxOAuth2\nsocial.backends.linkedin.LinkedinOAuth\nsocial.backends.github.GithubOAuth2\nsocial.backends.foursquare.FoursquareOAuth2\nsocial.backends.instagram.InstagramOAuth2\nsocial.backends.live.LiveOAuth2\nsocial.backends.vk.VKOAuth2\nsocial.backends.dailymotion.DailymotionOAuth2\nsocial.backends.disqus.DisqusOAuth2\nsocial.backends.dropbox.DropboxOAuth\nsocial.backends.eveonline.EVEOnlineOAuth2\nsocial.backends.evernote.EvernoteSandboxOAuth\nsocial.backends.flickr.FlickrOAuth\nsocial.backends.livejournal.LiveJournalOpenId\nsocial.backends.soundcloud.SoundcloudOAuth2\nsocial.backends.thisismyjam.ThisIsMyJamOAuth1\nsocial.backends.stocktwits.StocktwitsOAuth2\nsocial.backends.tripit.TripItOAuth\nsocial.backends.twilio.TwilioAuth\nsocial.backends.clef.ClefOAuth2\nsocial.backends.xing.XingOAuth\nsocial.backends.yandex.YandexOAuth2\nsocial.backends.podio.PodioOAuth2\nsocial.backends.reddit.RedditOAuth2\nsocial.backends.mineid.MineIDOAuth2\nsocial.backends.wunderlist.WunderlistOAuth2\nsocial.backends.saml.SAMLAuth', 'store.url': 'sqlite:////Users/Arthur/Projects/assembl/assembl.db', 'mail.tls': 'true', 'db_password': 'assembl', 'SOCIAL_AUTH_LOGIN_REDIRECT_URL': '/', 'offline_mode': 'false', 'celery_tasks.translate.num_workers': '1', 'new_frontend': 'true', 'beaker.session.type': 'ext:memcached', 'requirejs.cache_bust': 'true', 'SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE': 'profile email', 'pyramid.debug_authorization': 'true', 'SOCIAL_AUTH_GITHUB_KEY': '...', 'pyramid.debug_traversal': 'true', 'dogpile_cache.expiration_time': '10000', 'celery_tasks.source_reader.imodeleventwatcher': 'assembl.tasks.notification_dispatch.ModelEventWatcherCelerySender', 'assembl.validate_registration_emails': 'false', 'accept_secure_connection': 'false', 'smtp_host': 'localhost', 'source_reader_debug_signal': 'true', 'SOCIAL_AUTH_PROTECTED_USER_FIELDS': 'fullname', 'assembl.admin_email': 'webmaster@localhost', 'help_url': 'http://assembl.org/user-guides/', 'memcached_host': 'localhost', 'celery_tasks.notification_dispatch.imodeleventwatcher': 'assembl.models.notification.ModelEventWatcherNotificationSubscriptionDispatcher', 'sqltap': 'true', 'beaker.session.validate_key': '6M+EL51cKllnZGqWuAA2XJbhtqh8QW4X3q+GhTPys15ADaYpqn6gx0/BJdDrm/+w43Z+vU3Rb/OqqrMZdVTLEmx5', 'db_database': 'assembl', 'celery_tasks.notify.num_workers': '1', 'beaker.session.cookie_expires': 'false', 'minified_js': 'false', 'SOCIAL_AUTH_LOGIN_FUNCTION': 'assembl.auth.social_auth.login_user', 'beaker.session.key': 'assembl_session', 'beaker.session.session_class': 'assembl.auth.upgradable_session.AssemblUpgradableSession', 'beaker.session.data_dir': '/Users/Arthur/Projects/assembl/var/sessions/data', 'env.wsginame': 'dev.wsgi'}
keeping: {'mail.port': '8025', 'public_port': '6543', 'SOCIAL_AUTH_FACEBOOK_SCOPE': 'public_profile\nemail', 'SOCIAL_AUTH_TWITTER_SECRET': '...', 'celery_tasks.broker': 'redis://localhost:6379/0', 'pyramid.debug_traversal': 'true', 'pyramid.debug_all': 'true', 'config_uri': '/Users/Arthur/Projects/assembl/local.ini', 'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET': '...', 'changes.websocket.port': '8085', 'SOCIAL_AUTH_PROTECTED_USER_FIELDS': 'fullname', 'facebook.debug_mode': 'true', 'sqlalchemy.strategy': 'atexit_cleanup', 'facebook.export_permissions': 'public_profile, email, publish_actions, user_posts, user_likes, manage_pages, publish_pages, user_groups, user_managed_groups', 'SOCIAL_AUTH_WORDPRESS_OAUTH2_SECRET': '....', 'login_providers': 'facebook twitter google-oauth2', 'beaker.session.lock_dir': '/Users/Arthur/Projects/assembl/var/sessions/lock', 'auth_policy_class': 'assembl.auth.util.UpgradingTokenSessionAuthenticationPolicy', 'sqlalchemy.url': 'postgresql+psycopg2://assembl:assembl@localhost/assembl?sslmode=disable', 'SOCIAL_AUTH_SAML_SP_ENTITY_ID': 'http://saml.localhost', 'sqlalchemy.echo': 'False', 'pyramid.reload_templates': 'true', 'activate_tour': 'true', 'dogpile_cache.backend': 'file', 'elasticsearch_host': 'localhost', 'celery_tasks.imap.imodeleventwatcher': 'assembl.tasks.notification_dispatch.ModelEventWatcherCelerySender', 'mail.host': 'localhost', 'elasticsearch_index': 'assembl', 'redis_host': 'localhost', 'celery_tasks.notification_dispatch.num_workers': '1', 'SOCIAL_AUTH_FACEBOOK_SECRET': '...', 'SOCIAL_AUTH_FACEBOOK_KEY': '...', 'assembl_handle_exceptions': 'false', 'assembl.imodeleventwatcher': 'assembl.tasks.notification_dispatch.ModelEventWatcherCelerySender', 'assembl.validate_registration_emails': 'false', 'changes.multiplex': 'true', 'ini_files': 'production.ini develop_overlay.ini RANDOM:random.ini.tmpl RC_DATA', 'web_analytics_piwik_api_token': '', 'handle_exceptions': '', 'debugtoolbar.intercept_exc': 'display', 'db_schema': 'public', 'public_hostname': 'localhost', 'changes.websocket.proxied': 'false', 'session.secret': 'FTIapirL5xElIRn9nopUJEv5D8W/5UtqBndrv8xGHiYSQkNELZiq4jq2xS8WDjev25ZrvkHdI8scU7MghSIzddF5', 'raven_url': '', 'tm.attempts': '2', 'SOCIAL_AUTH_GITHUB_SECRET': '...', 'piwik_host': 'localhost', 'IGNORE_DEFAULT_SCOPE': 'True', 'SOCIAL_AUTH_AUTHENTICATION_BACKENDS': 'assembl.auth.wordpress.WordPressServerOAuth2\nsocial.backends.twitter.TwitterOAuth\nsocial.backends.open_id.OpenIdAuth\nsocial.backends.google.GoogleOpenId\nsocial.backends.google.GoogleOAuth2\nsocial.backends.google.GoogleOAuth\nsocial.backends.yammer.YammerOAuth2\nsocial.backends.yahoo.YahooOpenId\nsocial.backends.stripe.StripeOAuth2\nsocial.backends.persona.PersonaAuth\nsocial.backends.facebook.FacebookOAuth2\nsocial.backends.facebook.FacebookAppOAuth2\nsocial.backends.yahoo.YahooOAuth\nsocial.backends.angel.AngelOAuth2\nsocial.backends.behance.BehanceOAuth2\nsocial.backends.bitbucket.BitbucketOAuth\nsocial.backends.box.BoxOAuth2\nsocial.backends.linkedin.LinkedinOAuth\nsocial.backends.github.GithubOAuth2\nsocial.backends.foursquare.FoursquareOAuth2\nsocial.backends.instagram.InstagramOAuth2\nsocial.backends.live.LiveOAuth2\nsocial.backends.vk.VKOAuth2\nsocial.backends.dailymotion.DailymotionOAuth2\nsocial.backends.disqus.DisqusOAuth2\nsocial.backends.dropbox.DropboxOAuth\nsocial.backends.eveonline.EVEOnlineOAuth2\nsocial.backends.evernote.EvernoteSandboxOAuth\nsocial.backends.flickr.FlickrOAuth\nsocial.backends.livejournal.LiveJournalOpenId\nsocial.backends.soundcloud.SoundcloudOAuth2\nsocial.backends.thisismyjam.ThisIsMyJamOAuth1\nsocial.backends.stocktwits.StocktwitsOAuth2\nsocial.backends.tripit.TripItOAuth\nsocial.backends.twilio.TwilioAuth\nsocial.backends.clef.ClefOAuth2\nsocial.backends.xing.XingOAuth\nsocial.backends.yandex.YandexOAuth2\nsocial.backends.podio.PodioOAuth2\nsocial.backends.reddit.RedditOAuth2\nsocial.backends.mineid.MineIDOAuth2\nsocial.backends.wunderlist.WunderlistOAuth2\nsocial.backends.saml.SAMLAuth', 'use_elasticsearch': 'true', 'trusted_login_providers': 'facebook\ngoogle-oauth2\ntwitter\nsaml', 'pyramid.includes': '\npyramid_mailer.debug\npyramid_debugtoolbar\npyramid_debugtoolbar_ajax\npyramid_tm', 'use_webpack_server': 'true', 'SOCIAL_AUTH_FIELDS_STORED_IN_SESSION': 'next_view', 'web_analytics_piwik_url': '', 'beaker.session.url': 'localhost:11211', 'security.email_token_salt': 'FiMpWpy/GBs6jsQJq4+D1os97n+9sXxf6zaFJVYIonulX0kWqW7+atdEokBV1j0xa8pAlkydBoSKclvZ94guQKxW', 'avatar.gravatar_default': 'mm', 'beaker.session.cookie_on_exception': 'true', 'discussion_callbacks': '\nassembl.lib.discussion_creation.DiscussionCreationPrinter', 'SOCIAL_AUTH_LOGIN_URL': '/login', 'pyramid.debug_routematch': 'true', 'changes.socket': 'ipc:///tmp/assembl_changes/0', 'imap_host': 'localhost', 'changes.prefix': '/socket', 'SOCIAL_AUTH_GITHUB_SCOPE': 'repo', 'dogpile_cache.expiration_time': '10000', 'redis_socket': '0', 'pyramid.debug_notfound': 'true', 'changes.websocket.url': '//localhost:6543/socket/', 'debugtoolbar.enabled': 'true', 'assembl.admin_email': 'webmaster@localhost', 'beaker.session.elevated_expires': '2635200', 'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY': '...', 'default_theme': 'default', 'celery_tasks.imap.num_workers': '1', 'USE_UNIQUE_USER_ID': 'True', 'SOCIAL_AUTH_LOGGEDIN_FUNCTION': 'assembl.auth.social_auth.login_required', 'webpack_port': '8080', 'SOCIAL_AUTH_STORAGE': 'assembl.models.social_auth.AssemblStorage', 'SOCIAL_AUTH_USER_FIELDS': 'email\nfullname', 'mysql_host': 'localhost', 'assembl_debug_signal': 'true', 'use_source_reader_for_mail': 'false', 'supported_exports_list': '', 'SOCIAL_AUTH_STRATEGY': 'assembl.auth.social_auth.AssemblStrategy', 'store': 'sqlalchemy', 'SOCIAL_AUTH_LOGIN_REDIRECT_URL': '/', 'pyramid.default_locale_name': 'en_CA', 'accept_secure_connection': 'false', 'celery_tasks.translate.imodeleventwatcher': 'assembl.lib.model_watcher.ModelEventWatcherPrinter', 'available_languages': 'fr_CA en_CA de', 'webpack_host': 'localhost', 'dogpile_cache.arguments.filename': 'var/dogpile_cache.dbm', 'debugtoolbar.hosts': '127.0.0.0/8', 'beaker.session.type': 'ext:memcached', 'cache_viewdefs': 'false', 'SOCIAL_AUTH_WORDPRESS_OAUTH2_KEY': '....', 'web_analytics_piwik_script': '', 'require_secure_connection': 'false', 'SOCIAL_AUTH_USER_MODEL': 'assembl.models.auth.User', 'store.url': 'sqlite:////Users/Arthur/Projects/assembl/assembl.db', 'mail.tls': 'true', 'beaker.session.encrypt_key': '3FWsr87k7KtIzp3c9wBd5onSD0NVvnAC22v3ghP3ZDniI3umkslDSUkeBwZRAO3w7KlWiMgJaQNnFUKq1/SmKOMw', 'offline_mode': 'false', 'new_frontend': 'true', 'celery_tasks.translate.num_workers': '1', 'SOCIAL_AUTH_TWITTER_KEY': '...', 'requirejs.cache_bust': 'true', 'SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE': 'profile email', 'pyramid.debug_authorization': 'true', 'SOCIAL_AUTH_GITHUB_KEY': '...', 'subscriptions.participant.default': 'FOLLOW_SYNTHESES\nEMAIL_BOUNCED\nEMAIL_VALIDATE\nPARTICIPATED_FOR_FIRST_TIME_WELCOME\nSUBSCRIPTION_WELCOME', 'celery_tasks.source_reader.imodeleventwatcher': 'assembl.tasks.notification_dispatch.ModelEventWatcherCelerySender', 'random_file': 'random.ini', 'jinja2.directories': 'assembl:templates', 'smtp_host': 'localhost', 'source_reader_debug_signal': 'true', 'mac': 'false', 'celery_tasks.notify.imodeleventwatcher': 'assembl.lib.model_watcher.ModelEventWatcherPrinter', 'help_url': 'http://assembl.org/user-guides/', 'memcached_host': 'localhost', 'celery_tasks.notification_dispatch.imodeleventwatcher': 'assembl.models.notification.ModelEventWatcherNotificationSubscriptionDispatcher', 'sqltap': 'true', 'beaker.session.validate_key': '6M+EL51cKllnZGqWuAA2XJbhtqh8QW4X3q+GhTPys15ADaYpqn6gx0/BJdDrm/+w43Z+vU3Rb/OqqrMZdVTLEmx5', 'celery_tasks.notify.num_workers': '1', 'beaker.session.cookie_expires': 'false', 'minified_js': 'false', 'SOCIAL_AUTH_LOGIN_FUNCTION': 'assembl.auth.social_auth.login_user', 'beaker.session.key': 'assembl_session', 'beaker.session.session_class': 'assembl.auth.upgradable_session.AssemblUpgradableSession', 'beaker.session.data_dir': '/Users/Arthur/Projects/assembl/var/sessions/data', 'env.wsginame': 'dev.wsgi'}
ERROR: Initialized twice.
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'arthursw'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'Arthur Masson 2'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/Users/Arthur/Projects/assembl/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value 'arthurpub.sw@gmail.com'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
sent 0 * [{'@id': 'local:UserRole/2', '@private': 'local:AgentProfile/2', 'role': u'r:sysadmin', '@type': 'UserRole'}, {'username': 'arthursw', '@private': 'local:AgentProfile/2', 'verified': True, 'name': 'Arthur Masson 2', 'avatar_url_base': '/user/id/2/avatar/', 'creation_date': '2017-08-25T09:34:49.359269Z', 'accounts': [], 'real_name': 'Arthur Masson 2', '@id': 'local:AgentProfile/2', '@type': 'User', '@view': 'private', 'permissions': {}}, {'@id': 'local:AgentProfile/2', 'verified': True, '@type': 'User', 'name': 'Arthur Masson 2', 'creation_date': '2017-08-25T09:34:49.359269Z'}]
(venv) Arthur:assembl Arthur$ supervisorctl start dev:
dev:gulp: started
dev:webpack: started
dev:pserve: started
```

**Comment by arthursw** [comment]
And I still get `ERR_CONNECTION_REFUSED` on http://localhost:6543/

**Comment by vincentfretin** [comment]
You don't have to execute again assembl-add-user, the user is already in postgres. So this seems ok.
You have another error I think, see
`supervisorctl tail -f dev:pserve stderr`
my guess is you need to create elasticsearch index and reindex the contents with `assembl-reindex-all-contents local.ini` see https://github.com/assembl/assembl/blob/develop/doc/howtoupgrade.rst

**Comment by arthursw** [comment]
Ok ça fonctionne 👍
